services:
  app:
    user: node
    build:
      context: ./../
      dockerfile: ./.devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - "./../:/usr/src/app/"
    networks:
      - devnet

networks:
  devnet:
